// <auto-generated />
using System;
using GoiabadaAtomica.ApiAutenticacao.Net.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoiabadaAtomica.ApiAutenticacao.Net.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ContextoAplicacaoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GoiabadaAtomica.ApiAutenticacao.Net.Model.entity.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("tbl_roles", (string)null);
                });

            modelBuilder.Entity("GoiabadaAtomica.ApiAutenticacao.Net.Model.entity.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("tbl_users", (string)null);
                });

            modelBuilder.Entity("GoiabadaAtomica.ApiAutenticacao.Net.Model.entity.UserRoleEntity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("tbl_user_x_role", (string)null);
                });

            modelBuilder.Entity("GoiabadaAtomica.SistemaSeguranca.Api.Net.Model.Entity.AuthenticationProviderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientSystemId")
                        .HasColumnType("int");

                    b.Property<int?>("ConfigurationJson")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClientSystemId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tbl_authentication_providers", (string)null);
                });

            modelBuilder.Entity("GoiabadaAtomica.SistemaSeguranca.Api.Net.Model.Entity.ClientSystemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tbl_client_systems", (string)null);
                });

            modelBuilder.Entity("GoiabadaAtomica.SistemaSeguranca.Api.Net.Model.Entity.FeatureEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientSystemId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ClientSystemId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tbl_features", (string)null);
                });

            modelBuilder.Entity("GoiabadaAtomica.SistemaSeguranca.Api.Net.Model.Entity.PasswordPolicyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("ExpirationDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MinLength")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PasswordHistoryCount")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresDigit")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RequiresLowercase")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RequiresSpecialChar")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RequiresUppercase")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("tbl_password_policies", (string)null);
                });

            modelBuilder.Entity("GoiabadaAtomica.SistemaSeguranca.Api.Net.Model.Entity.RoleFeatureEntity", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.Property<int>("ClientSystemId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "FeatureId", "ClientSystemId");

                    b.HasIndex("ClientSystemId");

                    b.HasIndex("FeatureId");

                    b.ToTable("tbl_role_x_feature", (string)null);
                });

            modelBuilder.Entity("GoiabadaAtomica.SistemaSeguranca.Api.Net.Model.Entity.TenantEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("tbl_tenants", (string)null);
                });

            modelBuilder.Entity("GoiabadaAtomica.SistemaSeguranca.Api.Net.Model.Entity.UserProviderEntity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("AuthenticationProviderId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalIdentifier")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId", "AuthenticationProviderId");

                    b.HasIndex("AuthenticationProviderId");

                    b.ToTable("tbl_user_x_provider", (string)null);
                });

            modelBuilder.Entity("GoiabadaAtomica.ApiAutenticacao.Net.Model.entity.UserRoleEntity", b =>
                {
                    b.HasOne("GoiabadaAtomica.ApiAutenticacao.Net.Model.entity.RoleEntity", "Role")
                        .WithMany("UserRole")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoiabadaAtomica.ApiAutenticacao.Net.Model.entity.UserEntity", "User")
                        .WithMany("UserRole")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoiabadaAtomica.SistemaSeguranca.Api.Net.Model.Entity.AuthenticationProviderEntity", b =>
                {
                    b.HasOne("GoiabadaAtomica.SistemaSeguranca.Api.Net.Model.Entity.ClientSystemEntity", "ClientSystem")
                        .WithMany()
                        .HasForeignKey("ClientSystemId");

                    b.Navigation("ClientSystem");
                });

            modelBuilder.Entity("GoiabadaAtomica.SistemaSeguranca.Api.Net.Model.Entity.FeatureEntity", b =>
                {
                    b.HasOne("GoiabadaAtomica.SistemaSeguranca.Api.Net.Model.Entity.ClientSystemEntity", "ClientSystem")
                        .WithMany()
                        .HasForeignKey("ClientSystemId");

                    b.Navigation("ClientSystem");
                });

            modelBuilder.Entity("GoiabadaAtomica.SistemaSeguranca.Api.Net.Model.Entity.RoleFeatureEntity", b =>
                {
                    b.HasOne("GoiabadaAtomica.SistemaSeguranca.Api.Net.Model.Entity.ClientSystemEntity", "ClientSystem")
                        .WithMany()
                        .HasForeignKey("ClientSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoiabadaAtomica.SistemaSeguranca.Api.Net.Model.Entity.FeatureEntity", "Feature")
                        .WithMany("RoleFeature")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoiabadaAtomica.ApiAutenticacao.Net.Model.entity.RoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientSystem");

                    b.Navigation("Feature");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GoiabadaAtomica.SistemaSeguranca.Api.Net.Model.Entity.UserProviderEntity", b =>
                {
                    b.HasOne("GoiabadaAtomica.SistemaSeguranca.Api.Net.Model.Entity.AuthenticationProviderEntity", "AuthenticationProvider")
                        .WithMany()
                        .HasForeignKey("AuthenticationProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoiabadaAtomica.ApiAutenticacao.Net.Model.entity.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthenticationProvider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoiabadaAtomica.ApiAutenticacao.Net.Model.entity.RoleEntity", b =>
                {
                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("GoiabadaAtomica.ApiAutenticacao.Net.Model.entity.UserEntity", b =>
                {
                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("GoiabadaAtomica.SistemaSeguranca.Api.Net.Model.Entity.FeatureEntity", b =>
                {
                    b.Navigation("RoleFeature");
                });
#pragma warning restore 612, 618
        }
    }
}
